In [1]:
import numpy as np

# NumPy Reshaping and Resizing

Reference: https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

In [6]:
# Original array with sahpe 2 rows and 3 columns (2x3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array (2x3):\n", arr)

# Reshaping Arrays
# Changing the shape of the array to 3 rows and 2 columns.
reshaped_arr = arr.reshape((3, 2))
print("\nReshaped array (3x2):\n", reshaped_arr)

# Flattening Arrays
# Converting a multi-dimensional array into a 1D array.
flattened_arr = arr.flatten()
print("\nFlattened array:", flattened_arr)

# Transposing Arrays
# Swapping the dimensions of the array (rows become columns and vice versa).
transposed_arr = arr.T
print("\nTransposed array:\n", transposed_arr)

# Resizing Arrays
# Changing the size of the array to 3 rows and 3 columns.
# Note: This may repeat elements if the new size is larger than the original.
arr_resized = np.resize(arr, (3, 3))
print("\nResized array (3x3):\n", arr_resized)


Original array (2x3):
 [[1 2 3]
 [4 5 6]]

Reshaped array (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Flattened array: [1 2 3 4 5 6]

Transposed array:
 [[1 4]
 [2 5]
 [3 6]]

Resized array (3x3):
 [[1 2 3]
 [4 5 6]
 [1 2 3]]
