In [1]:
import numpy as np

In [4]:
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
m[[0,-1],:]

array([[1, 2, 3],
       [7, 8, 9]])

In [12]:
m[:,[0,-1]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [14]:
m[[0,-1],[0,0]]

array([1, 7])

In [16]:
import numpy as np

# Create the indices for rows and columns
rows = [0, -1]
cols = [0, -1]

# Use np.ix_ to create the meshgrid
meshgrid = np.ix_(rows, cols)

# Print the generated meshgrid
print("Meshgrid generated by np.ix_([0, -1], [0, -1]):")
print("Row indices:\n", meshgrid[0])
print("Column indices:\n", meshgrid[1])

# To visualize how it indexes into the original array, create the array
arr = np.arange(1, 10).reshape(3, 3)
print("\nOriginal array:\n", arr)

# Use the meshgrid to extract the corner elements
corner_elements = arr[meshgrid]
print("Corner elements arranged in 2x2 array:\n", corner_elements)


Meshgrid generated by np.ix_([0, -1], [0, -1]):
Row indices:
 [[ 0]
 [-1]]
Column indices:
 [[ 0 -1]]

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Corner elements arranged in 2x2 array:
 [[1 3]
 [7 9]]


In [22]:
# Define the scores array
scores = np.array([
    [4, 1],
    [2, 0],
    [3, 0],
    [5, 1],
    [6, 1]
])

# Define the categories
categories = ['bad', 'good']

In [23]:
good = scores[:, 1] == 1
bad = scores[:, 1] == 0
print(good)
scores[good, 0]

array([4, 5, 6])